# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date
  windows:
    runs-on: windows-latest
    steps:
      - name: Print Date
        run: date
  macos:
    runs-on: macos-latest
    steps:
      - name: Print Date
        run: date

  depends:
    runs-on: windows-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: Print Date
        run: date
